name: wave_builder
description: A utility for building a wave file by concatenating wave files and periods of silence.
version: 1.0.4
homepage: https://github.com/timkellypa/wave_builder

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
